### ISSUE TITLE
FRPS 仪表板开启 TLS 后，无法获取数据

### ISSUE THREAD

**Issue by Yang2635** [yhl452493373/frps-panel#1]
插件默认是 HTTP 请求访问获取数据，FRPS 仪表板开启 TLS 后，无法使用 HTTPS 请求数据。

`frps.ini` 相关配置如下：

```
……
#仪表板 TLS 模式
dashboard_tls_mode = true
dashboard_tls_cert_file = /xxx/fullchain.pem
dashboard_tls_key_file = /xxx/privkey.pem
```

取消仪表板 TLS 后使用默认方式可正常获取数据。

**Comment by yhl452493373** [comment]
dashboard的TLS没做处理，因是通过代理到frps-panel本机，然后frps-panel通过内网访问的frps的接口。通过frps-panel就能直接看到dashboard所有数据，我觉得可以直接把dashboard的ip改为127.0.0.1，禁止外网连接，然后把dashboard的tls关掉。后续如果这种需求确实很多的话，我再处理这个。如果为了https的话，干脆直接frps-panel加个tls

**Comment by yhl452493373** [comment]
> 插件默认是 HTTP 请求访问获取数据，FRPS 仪表板开启 TLS 后，无法使用 HTTPS 请求数据。
> 
> `frps.ini` 相关配置如下：
> 
> ```
> ……
> #仪表板 TLS 模式
> dashboard_tls_mode = true
> dashboard_tls_cert_file = /xxx/fullchain.pem
> dashboard_tls_key_file = /xxx/privkey.pem
> ```
> 
> 取消仪表板 TLS 后使用默认方式可正常获取数据。

我加了tls，你可以先测试下。

如果你需要直接https访问frps-panel，则common下增加如下配置：
```ini
[common]
tls_mode = true
tls_cert_file = cert.crt
tls_key_file = cert.key
```

这里的文件默认和`frps-panel.ini`处于同目录，也可以自行配置绝对路径

如果你frps的仪表板启用了tls，在common下增加 如下配置:

```ini
[common]
dashboard_tls = true
```

`dashboard_tls = true`的时候会跳过https的服务器证书验证。

---

[frps-panel-darwin-amd64.zip](https://github.com/yhl452493373/frps-panel/files/12574967/frps-panel-darwin-amd64.zip)
[frps-panel-freebsd-386.zip](https://github.com/yhl452493373/frps-panel/files/12574968/frps-panel-freebsd-386.zip)
[frps-panel-freebsd-amd64.zip](https://github.com/yhl452493373/frps-panel/files/12574969/frps-panel-freebsd-amd64.zip)
[frps-panel-linux-386.zip](https://github.com/yhl452493373/frps-panel/files/12574970/frps-panel-linux-386.zip)
[frps-panel-linux-amd64.zip](https://github.com/yhl452493373/frps-panel/files/12574971/frps-panel-linux-amd64.zip)
[frps-panel-linux-arm.zip](https://github.com/yhl452493373/frps-panel/files/12574972/frps-panel-linux-arm.zip)
[frps-panel-linux-arm64.zip](https://github.com/yhl452493373/frps-panel/files/12574974/frps-panel-linux-arm64.zip)
[frps-panel-linux-mips.zip](https://github.com/yhl452493373/frps-panel/files/12574976/frps-panel-linux-mips.zip)
[frps-panel-linux-mips64.zip](https://github.com/yhl452493373/frps-panel/files/12574977/frps-panel-linux-mips64.zip)
[frps-panel-linux-mips64le.zip](https://github.com/yhl452493373/frps-panel/files/12574978/frps-panel-linux-mips64le.zip)
[frps-panel-linux-mipsle.zip](https://github.com/yhl452493373/frps-panel/files/12574979/frps-panel-linux-mipsle.zip)
[frps-panel-windows-386.exe.zip](https://github.com/yhl452493373/frps-panel/files/12574980/frps-panel-windows-386.exe.zip)
[frps-panel-windows-amd64.exe.zip](https://github.com/yhl452493373/frps-panel/files/12574981/frps-panel-windows-amd64.exe.zip)

**Comment by Yang2635** [comment]
测试可以使用了
