### ISSUE TITLE
建议提供 Docker 镜像部署方式

### ISSUE THREAD

**Issue by jikunchong** [yhl452493373/frps-panel#5]
建议参考 frps/c 的容器镜像，提供 frps/c-panel，这样两者都用 Docker 部署更方便些，避免去配置 systemd 服务那些。

```shell
FRP_VER=0.51.3
FRP_PREFIX=domain
sudo docker pull fatedier/frps:v${FRP_VER}

sudo docker run -d --name frps-${FRP_PREFIX} --restart always \
  --network host \
  -v /data/app/frp/${FRP_PREFIX}/frps.ini:/etc/frp/frps.ini \
  -v /data/app/frp/${FRP_PREFIX}/frps.log:/var/log/frp/frps.log \
  -v /data/app/frp/404.html:/etc/frp/404.html \
  -v /etc/timezone:/etc/timezone:ro \
  -v /etc/localtime:/etc/localtime:ro \
  fatedier/frps:v${FRP_VER} -c /etc/frp/frps.ini
```

**Comment by yhl452493373** [comment]
> 建议参考 frps/c 的容器镜像，提供 frps/c-panel，这样两者都用 Docker 部署更方便些，避免去配置 systemd 服务那些。
> 
> ```shell
> FRP_VER=0.51.3
> FRP_PREFIX=domain
> sudo docker pull fatedier/frps:v${FRP_VER}
> 
> sudo docker run -d --name frps-${FRP_PREFIX} --restart always \
>   --network host \
>   -v /data/app/frp/${FRP_PREFIX}/frps.ini:/etc/frp/frps.ini \
>   -v /data/app/frp/${FRP_PREFIX}/frps.log:/var/log/frp/frps.log \
>   -v /data/app/frp/404.html:/etc/frp/404.html \
>   -v /etc/timezone:/etc/timezone:ro \
>   -v /etc/localtime:/etc/localtime:ro \
>   fatedier/frps:v${FRP_VER} -c /etc/frp/frps.ini
> ```

这玩意儿用不着一个docker了吧。

本身就没啥配置，也不需要额外安装什么环境，随便一个命令就能跑，装服务也就建一个frps-panel.service的问题。

**Comment by jikunchong** [comment]
好吧，我自己打包
