### ISSUE TITLE
设置了用户的端口范围但是实际并没有限制

### ISSUE THREAD

**Issue by wsw54188** [yhl452493373/frps-panel#6]
比如说我限制用户user1的端口范围为10000-10010，但在实际使用中user1新建了一个11111端口的并成功映射，在后台也能看到11111端口在线。实际并未实现端口限制，大佬有空可以试一下，

**Comment by yhl452493373** [comment]
等我最近忙过了。。10月份工作有点忙

**Comment by mourenZhu** [comment]
更新最新的版本，现在已经可以了

**Comment by wzshuang** [comment]
我也遇到了类似的问题。允许的端口是58081，但是用58082也可以连接成功。

![image](https://github.com/yhl452493373/frps-panel/assets/8585771/a7e9334a-f198-4f31-8392-a642f9b28b36)
![image](https://github.com/yhl452493373/frps-panel/assets/8585771/618d59fa-a958-4f0c-b5a9-a6c493631a1f)

**Comment by zzbamboo** [comment]
最新合并的我提交的内容已经修复了这个问题

**Comment by wsw54188** [comment]
可以发个Releases吗

**Comment by yhl452493373** [comment]
已更新，可以试一下
